{
    'name': 'Sistema Planilla v5.28.51-PROD',
<<<<<<< HEAD
    'version': '19.0.5.28.149',
=======
    'version': '19.0.5.28.147',
>>>>>>> 7ecff5836349c6236dca581bb6605277771818e5
    
    'category': 'Human Resources/Payroll',
    'summary': 'Sistema de Planilla Costa Rica v5.14 - Legislacion CR 2026',
    'description': """
        Modulo completo de gestion de planillas para Costa Rica.
        Incluye:
        - Gestion de empleados con tipos, estados y puestos
        - Codigos de deduccion (CCSS, INS, renta, etc.)
        - Calendarizaciones de pago (semanal, quincenal, mensual)
        - Horas extras, incapacidades y vacaciones
        - Boletas de pago con envio automatico por correo
        - Historial de salarios por colaborador
        - Soporte para multiples sucursales
        - Integracion contable completa (por empleado o por planilla)
        - Dashboard con metricas del mes
        - Reportes PDF: Resumen Mensual, CCSS, Costo por Sucursal, Detalle Empleado
    """,
    'author': 'Planilla CR',
    'website': '',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'hr',
        'hr_attendance',
        'hr_holidays',
        'account',
        'mail',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/identification_type_data.xml',
        'data/income_tax_data.xml',
        'data/minimum_salary_data.xml',
        'data/deduction_code_data.xml',
        'data/leave_cr_data.xml',
        'data/default_data.xml',
        'data/charge_type_data.xml',
        'views/income_tax_bracket_views.xml',
        'views/minimum_salary_views.xml',
        'views/employee_loan_views.xml',
        'views/branch_views.xml',
        'views/identification_type_views.xml',
        'views/employee_status_views.xml',
        'views/employee_type_views.xml',
        'views/deduction_code_views.xml',
        'views/schedule_type_views.xml',
        'views/payroll_calendar_views.xml',
        'views/accounting_config_views.xml',
        'views/closed_period_views.xml',
        'views/hr_employee_extension_views.xml',
        'views/overtime_views.xml',
        'views/disability_views.xml',
        'views/vacation_payment_views.xml',
        'views/pension_alimentaria_views.xml',
        'views/termination_views.xml',
        'views/embargo_views.xml',
        'views/bono_views.xml',
        'views/leave_cr_views.xml',
        'views/bono_antiguedad_config_views.xml',
        'views/employee_charge_views.xml',
        'views/employee_movement_views.xml',
        'views/payslip_cr_views.xml',
        'views/payroll_run_cr_views.xml',
        'views/salary_history_views.xml',
        'views/dashboard_report_views.xml',
        'report/termination_report.xml',
        'report/loan_report.xml',
        'report/vacation_balance_report.xml',
        'report/employer_cost_report.xml',
        'report/overtime_consolidated_report.xml',
        'report/payslip_report.xml',
        'report/salary_history_report.xml',
        'report/payroll_reports.xml',
        'report/ins_report.xml',
        'report/ccss_report.xml',
        'report/employee_charge_report.xml',
        'report/amonestacion_report.xml',
        'report/constancia_despido_report.xml',
        'views/ins_report_views.xml',
        'views/bank_payment_views.xml',
        'views/ccss_report_views.xml',
        'wizard/send_payslip_wizard_views.xml',
        'wizard/migrate_codes_wizard_views.xml',
        'wizard/test_email_wizard_views.xml',
        'wizard/salary_increase_wizard_views.xml',
        'views/import_overtime_wizard_views.xml',
        'views/public_holiday_views.xml',
        'wizard/vacation_balance_wizard_views.xml',
        'wizard/employer_cost_wizard_views.xml',
        'wizard/wizard_views_v24.xml',
        'wizard/aguinaldo_wizard_views.xml',
        'wizard/import_template_wizard_views.xml',
        'wizard/sync_hr_wizard_views.xml',
        'wizard/import_data_wizard_views.xml',
        'data/cron_jobs.xml',
        'data/email_templates.xml',
        'data/public_holidays_cr.xml',
        'views/eddi7_export_views.xml',
        'views/amonestacion_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'images': ['static/description/icon.png'],
    'post_init_hook': 'post_init_hook',
    'post_migrate_hook': 'post_migrate_hook',
    'external_dependencies': {'python': ['openpyxl']},
}